feat: add input type number
chocofamilyme/choco-ui pull request #106
Opened 2022-09-29 05:04 UTC by a-baktybay

- добавил возможноcть менять input type 
- @KirIIISolovyov

2022-09-29 06:30 UTC, KirIIISolovyov requested changes

2022-09-29 06:30 UTC, KirIIISolovyov commented on src/components/ChInput/ChInput.vue
> +            :is="'input'"
**nitpick:** Теперь component будет только input? Если да, то давай удалим тэг `component` на `input`.

2022-09-29 06:30 UTC, KirIIISolovyov commented on src/components/ChInput/ChInput.vue
> +            :is="'input'"
PS: изменения в этом MR breaking, т.е при установке новой версии библиотеки код сломается. В целом, это ок, т.к библиотека в активной разработке, но лучше в MR описывать почему нужно было вносить эти изменения

2022-09-29 06:31 UTC, KirIIISolovyov commented
@a-baktybay лучше в названии и описании указывать какой компонент изменяется, а то приходится в коде смотреть какой компонент был изменен, а потом уже понимать что это за MR

2022-10-05 09:02 UTC, KirIIISolovyov commented
@kate-timofeyeva Можешь, пожалуйста, проверить этот MR?

2022-10-05 09:10 UTC, kate-timofeyeva approved these changes

2022-10-05 09:10 UTC, kate-timofeyeva commented on src/components/ChInput/ChInput.stories.mdx
> +| disabled      | Boolean              | Optional. Заблокрован ли input                                        |
**suggestion:** Думаю стоит вынести `Optional` в отдельный столбик и `emits` сразу прописать

2022-10-05 09:40 UTC, KirIIISolovyov commented on src/components/ChInput/ChInput.stories.mdx
> +| disabled      | Boolean              | Optional. Заблокрован ли input                                        |
Исправил в [e7d2283](https://github.com/chocofamilyme/choco-ui/pull/106/commits/e7d2283618164c9bc434dcaa31a3cbb7b79f4f36)

2022-10-05 09:44 UTC, KirIIISolovyov approved these changes

2022-10-05 10:34 UTC, merged