refactor(toggle-button): use slots
chocofamilyme/choco-ui pull request #77
Opened 2022-07-29 10:13 UTC by a-baktybay

2022-08-01 08:22 UTC, KirIIISolovyov commented
**nitpick:** package-lock.json установили со старой версией node. @a-baktybay переключись, пожалуйста, на node16+ и установи пакеты заново (если не нужно устанавливать новые пакеты, то лучше откатить коммит с package-lock.json или скопировать с main и заменить)

2022-08-01 08:34 UTC, KirIIISolovyov requested changes
**thought(non-blocking):** Думаю, что не хватает документации. Нужно добавить либо в этом MR либо создать Issue с документацией

2022-08-01 08:34 UTC, KirIIISolovyov commented on src/components/ChToggleButton/ChToggleButton.vue
> +  >
**praise:** Молодец, что реализовал через `button`. Вообще, странно, что с самого начала кнопка была реализована через `div`:thumbsup:

2022-08-01 08:34 UTC, KirIIISolovyov commented on src/components/ChToggleButton/ChToggleButton.vue
> +    @click="onClick(id)"
**thought:** Наверное, стоит добавить type="button", т.к эта кнопка по функционалу вряд ли когда либо будет использоваться для отправки формы. Случаев, когда она будет использоваться как обычная кнопка больше, поэтому, мне кажется, стоит добавить `type="button"`

2022-08-01 08:37 UTC, a-baktybay commented on src/components/ChToggleButton/ChToggleButton.vue
> +}
нет, не получится, тоже думал насчет этого. Там хранится id который сравнивается с id который я передаю(currentId === id)

2022-08-02 04:44 UTC, KirIIISolovyov approved these changes

2022-08-02 05:00 UTC, closed without merging